---
authors: FedMed Team <dev@fedmed.org>
name: "FedMed Flower Client v0.1.0"
description:
  Runs a single Flower NumPyClient inside CUBE. Launch this pipeline once per
  participating site while the FedMed Flower Server pipeline is still running,
  overriding `--cid`/`--total-clients` (and optionally `--server-host`) as
  needed.
category: Federated Learning
locked: false
plugin_tree:
  - title: run-flower-client
    plugin: fl-client v0.1.0
    previous: ~
    plugin_parameter_defaults:
      cid: 0
      total_clients: 1
      server_host: 172.17.0.2
      server_port: 9091
      learning_rate: 0.2
      epochs: 10
      seed: 13
      metrics_file: client_metrics.json
