---
authors: FedMed Team <dev@fedmed.org>
name: "FedMed Flower SuperLink v0.2.0"
description:
  Launches the Flower SuperLink inside CUBE. Run this pipeline once for each
  federated training session, then trigger the SuperNode pipeline(s) while the
  SuperLink job is still active.
category: Federated Learning
locked: false
plugin_tree:
  - title: start-flower-server
    plugin: fl-superlink v0.2.0
    previous: ~
    plugin_parameter_defaults:
      host: 0.0.0.0
      fleet_port: 9092
      control_port: 9093
      serverapp_port: 9091
      rounds: 1
      total_clients: 1
      local_epochs: 10
      learning_rate: 0.2
      data_seed: 13
      fraction_evaluate: 1.0
      summary_file: server_summary.json
